name: myportfolio
description: "My personal portfolio."
publish_to: "none"
version: 2.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  google_fonts: ^6.1.0
  ming_cute_icons: ^0.0.5
  provider: ^6.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/development/
    - assets/images/projects/
    - assets/images/projects/compose/
    - assets/images/projects/flutter/
    - assets/images/projects/react/
    - assets/images/projects/xml/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
