name: myportfolio
description: "My personal portfolio."
publish_to: "none"
version: 2.2.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  google_fonts: ^6.3.0
  ming_cute_icons: ^0.0.7
  provider: ^6.1.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  logger: ^2.6.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/development/
    - assets/images/projects/
    - assets/images/projects/compose/
    - assets/images/projects/flutter/
    - assets/images/projects/react/
    - assets/images/projects/xml/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
